version: '2'

services:
  minecraft:
    image: openjdk:8-jdk
    working_dir: /opt/java
    command: java -jar CHANGEME.jar
    ports:
      - 25565:25565
    volumes:
      - ./java:/opt/java
    restart: always
